name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        run: golangci-lint run

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v

      - name: Upload JUnit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: junit.xml

  publish-test-results:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: junit.xml
          token: ${{ secrets.GITHUB_TOKEN }}