name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.5' # Use the Go version from your go.mod file or specify manually

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v
